id: P005588
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 12:05:04.030520
source_metadata:
  id: bdr:W1KG14740
  title: ཆོས་རྒྱལ་ནོར་བཟང་གི་རྣམ་ཐར།
  author: ''
  volumes:
    f51441e1ad51444c905b99bf1d5d6c84:
      image_group_id: I2PD18218
      title: ''
      volume_number: 1
      total_pages: 428
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
